name = "armstrong"
license = "MIT"
licenselink = "https://github.com/gnalck/armstrong/blob/master/LICENSE.md"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.70

[author]
  name = "Kevin Lang"
  homepage = "https://gnalck.com/"
  twitter = "https://twitter.com/gnalck"

